services:
  frontend:
    build:
      context: ./frontend
      args:
        BUILD_TIME: "${BUILD_TIME:-$(date +%s)}"
    container_name: hance-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    build:
      context: ./backend
      args:
        BUILD_TIME: "${BUILD_TIME:-$(date +%s)}"
    container_name: hance-backend
    ports:
      - "10.0.2.22:8000:8000"
    env_file:
      - ./backend/.env
    networks:
      - app-network
    volumes:
      - backend-data:/app/data
      - ./backend/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://10.0.2.22:8000/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge

volumes:
  backend-data: